FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY packages/shared/package.json ./packages/shared/
COPY services/ui/package.json ./services/ui/

RUN --mount=type=cache,target=/root/.npm,sharing=locked npm install

COPY packages/shared ./packages/shared
COPY services/ui ./services/ui

RUN npm run build --workspace=packages/shared

WORKDIR /app/services/ui

CMD ["npm", "run", "dev"]
