FROM node:20-alpine
WORKDIR /app
COPY package.json tsconfig.json ./
COPY packages/shared/package.json ./packages/shared/
COPY services/api-service/package.json ./services/api-service/
COPY services/analyser-service/package.json ./services/analyser-service/
RUN --mount=type=cache,target=/root/.npm npm install
WORKDIR /app/services/api-service
CMD ["npx", "tsx", "watch", "src/index.ts"]
